// Code generated by "stringer -type=Weather"; DO NOT EDIT.

package csp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LightThunderstorm-0]
	_ = x[Thunderstorm-1]
	_ = x[HeavyThunderstorm-2]
	_ = x[LightDrizzle-3]
	_ = x[Drizzle-4]
	_ = x[HeavyDrizzle-5]
	_ = x[LightRain-6]
	_ = x[Rain-7]
	_ = x[HeavyRain-8]
	_ = x[LightSnow-9]
	_ = x[Snow-10]
	_ = x[HeavySnow-11]
	_ = x[LightSleet-12]
	_ = x[Sleet-13]
	_ = x[HeavySleet-14]
	_ = x[Clear-15]
	_ = x[FewClouds-16]
	_ = x[ScatteredClouds-17]
	_ = x[BrokenClouds-18]
	_ = x[OvercastClouds-19]
	_ = x[Fog-20]
	_ = x[Mist-21]
	_ = x[Smoke-22]
	_ = x[Haze-23]
	_ = x[Sand-24]
	_ = x[Dust-25]
	_ = x[Squalls-26]
	_ = x[Tornado-27]
	_ = x[Hurricane-28]
	_ = x[Cold-29]
	_ = x[Hot-30]
	_ = x[Windy-31]
	_ = x[Hail-32]
}

const _Weather_name = "LightThunderstormThunderstormHeavyThunderstormLightDrizzleDrizzleHeavyDrizzleLightRainRainHeavyRainLightSnowSnowHeavySnowLightSleetSleetHeavySleetClearFewCloudsScatteredCloudsBrokenCloudsOvercastCloudsFogMistSmokeHazeSandDustSquallsTornadoHurricaneColdHotWindyHail"

var _Weather_index = [...]uint16{0, 17, 29, 46, 58, 65, 77, 86, 90, 99, 108, 112, 121, 131, 136, 146, 151, 160, 175, 187, 201, 204, 208, 213, 217, 221, 225, 232, 239, 248, 252, 255, 260, 264}

func (i Weather) String() string {
	if i >= Weather(len(_Weather_index)-1) {
		return "Weather(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weather_name[_Weather_index[i]:_Weather_index[i+1]]
}
